export {
    DEFAULT_WEBCAM_SETTINGS,
    GRBL_ALARM_CODES,
    GRBL_ERROR_CODES,
    DEFAULT_MACROS,
    DEFAULT_TOOLS,
    DEFAULT_SETTINGS,
    DEFAULT_GENERATOR_SETTINGS,
    GRBL_REALTIME_COMMANDS
} from '@mycnc/shared';
